import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const result = await build({
  entryPoints: [resolve(root, "src/report/viewer.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  write: false,
  minify: process.env.NODE_ENV === "production",
  logLevel: "warning",
});

const js = result.outputFiles[0].text;
const css = await readFile(resolve(root, "src/report/viewer.css"), "utf8");

const out = `// Auto-generated by scripts/build-viewer.mjs — DO NOT EDIT.
export const VIEWER_JS: string = ${JSON.stringify(js)};
export const VIEWER_CSS: string = ${JSON.stringify(css)};
`;

await writeFile(resolve(root, "src/report/_bundle.ts"), out, "utf8");
console.log(
  `[build-viewer] wrote _bundle.ts (${(js.length / 1024).toFixed(1)} KB JS, ${(css.length / 1024).toFixed(1)} KB CSS)`,
);
